-- MySQL Script generated by MySQL Workbench
-- qui 23 abr 2020 19:29:15 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema etl_despesa_publica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `etl_despesa_publica` ;

-- -----------------------------------------------------
-- Schema etl_despesa_publica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `etl_despesa_publica` DEFAULT CHARACTER SET utf8 ;
USE `etl_despesa_publica` ;

-- -----------------------------------------------------
-- Table `etl_despesa_publica`.`TBL_DIMENSAO_ORGAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_ORGAO` ;

CREATE TABLE IF NOT EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_ORGAO` (
  `PK_ORGAO` INT(11) NOT NULL AUTO_INCREMENT,
  `CD_ORGAO_SUPERIOR` INT(11) NULL,
  `NM_ORGAO_SUPERIOR` VARCHAR(100) NULL,
  `CD_ORGAO_SUBORDINADO` INT(11) NULL,
  `NM_ORGAO_SUBORDINADO` VARCHAR(100) NULL,
  `CD_UNIDADE_ORCAMENTARIA` INT(11) NULL,
  `NM_UNIDADE_ORCAMENTARIA` VARCHAR(100) NULL,
  PRIMARY KEY (`PK_ORGAO`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `PK_ORGAO_UNIQUE` ON `etl_despesa_publica`.`TBL_DIMENSAO_ORGAO` (`PK_ORGAO` ASC);


-- -----------------------------------------------------
-- Table `etl_despesa_publica`.`TBL_DIMENSAO_PROGRAMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_PROGRAMA` ;

CREATE TABLE IF NOT EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_PROGRAMA` (
  `PK_PROGRAMA` INT(11) NOT NULL AUTO_INCREMENT,
  `CD_PROGRAMA_ORCAMENTARIO` INT(11) NULL,
  `NM_PROGRAMA_ORCAMENTARIO` VARCHAR(100) NULL,
  `CD_ACAO` VARCHAR(10) NULL,
  `NM_ACAO` VARCHAR(150) NULL,
  PRIMARY KEY (`PK_PROGRAMA`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `PK_PROGRAMA_UNIQUE` ON `etl_despesa_publica`.`TBL_DIMENSAO_PROGRAMA` (`PK_PROGRAMA` ASC);


-- -----------------------------------------------------
-- Table `etl_despesa_publica`.`TBL_DIMENSAO_TEMPORAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_TEMPORAL` ;

CREATE TABLE IF NOT EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_TEMPORAL` (
  `PK_TEMPORAL` INT(11) NOT NULL AUTO_INCREMENT,
  `MES` INT NULL,
  `ANO` INT NULL,
  PRIMARY KEY (`PK_TEMPORAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etl_despesa_publica`.`TBL_DIMENSAO_AREA_ATUACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_AREA_ATUACAO` ;

CREATE TABLE IF NOT EXISTS `etl_despesa_publica`.`TBL_DIMENSAO_AREA_ATUACAO` (
  `PK_AREA_ATUACAO` INT NOT NULL AUTO_INCREMENT,
  `CD_FUNCAO` INT(11) NULL,
  `NM_FUNCAO` VARCHAR(45) NULL,
  `CD_SUBFUNCAO` INT(11) NULL,
  `NM_SUBFUNCAO` VARCHAR(100) NULL,
  PRIMARY KEY (`PK_AREA_ATUACAO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etl_despesa_publica`.`TBL_FATO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etl_despesa_publica`.`TBL_FATO` ;

CREATE TABLE IF NOT EXISTS `etl_despesa_publica`.`TBL_FATO` (
  `FK_ORGAO` INT(11) NOT NULL,
  `FK_PROGRAMA` INT(11) NOT NULL,
  `FK_TEMPORAL` INT(11) NOT NULL,
  `FK_AREA_ATUACAO` INT NOT NULL,
  `VLR_LIQUIDADO` DECIMAL(15,2) NULL,
  `VLR_ORCADO` DECIMAL(15,2) NULL,
  CONSTRAINT `fk_TBL_FATO_TBL_DIMENSAO_ORGAO`
    FOREIGN KEY (`FK_ORGAO`)
    REFERENCES `etl_despesa_publica`.`TBL_DIMENSAO_ORGAO` (`PK_ORGAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_FATO_TBL_DIMENSAO_PROGRAMA1`
    FOREIGN KEY (`FK_PROGRAMA`)
    REFERENCES `etl_despesa_publica`.`TBL_DIMENSAO_PROGRAMA` (`PK_PROGRAMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_FATO_TBL_DIMENSAO_TEMPORAL1`
    FOREIGN KEY (`FK_TEMPORAL`)
    REFERENCES `etl_despesa_publica`.`TBL_DIMENSAO_TEMPORAL` (`PK_TEMPORAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_FATO_TBL_DIMENSAO_AREA_ATUACAO1`
    FOREIGN KEY (`FK_AREA_ATUACAO`)
    REFERENCES `etl_despesa_publica`.`TBL_DIMENSAO_AREA_ATUACAO` (`PK_AREA_ATUACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TBL_FATO_TBL_DIMENSAO_ORGAO_idx` ON `etl_despesa_publica`.`TBL_FATO` (`FK_ORGAO` ASC);

CREATE INDEX `fk_TBL_FATO_TBL_DIMENSAO_PROGRAMA1_idx` ON `etl_despesa_publica`.`TBL_FATO` (`FK_PROGRAMA` ASC);

CREATE INDEX `fk_TBL_FATO_TBL_DIMENSAO_TEMPORAL1_idx` ON `etl_despesa_publica`.`TBL_FATO` (`FK_TEMPORAL` ASC);

CREATE INDEX `fk_TBL_FATO_TBL_DIMENSAO_AREA_ATUACAO1_idx` ON `etl_despesa_publica`.`TBL_FATO` (`FK_AREA_ATUACAO` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
